# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 05:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_auto_20170115_0447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadenzauser',
            name='tracker_name',
        ),
    ]
