# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 20:44
from __future__ import unicode_literals

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0003_remove_cadenzauser_tracker_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadenzauser',
            name='mobile',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, unique=True),
        ),
    ]
